[package]
name = "EDR-Generator"
version = "0.1.0"
authors = ["x24git <23037854+x24git@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
